# Generated by Django 4.0.4 on 2022-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_page', '0002_alter_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
