# Generated by Django 4.0.4 on 2022-04-29 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables_page', '0004_alter_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
